		
	---B13.2: g_awt_ACCOUNTS
create dynamic asynchronous writethrough global cache group g_awt_ACCOUNTS from
FOPRO.ACCOUNTS(
ACCTNO         VARCHAR2(12) ,
	ACTYPE         VARCHAR2(20) ,
	CUSTODYCD      VARCHAR2(12) ,
	POLICYCD       VARCHAR2(20) ,
	GRNAME         VARCHAR2(20) ,
	ACCLASS        VARCHAR2(18) ,
	FORMULACD      VARCHAR2(20) ,
	POOLID         VARCHAR2(20) ,
	ROOMID         VARCHAR2(20) ,
	BASKETID       VARCHAR2(60) ,
	BASKETID_UB    VARCHAR2(60) ,
	STATUS         CHAR(1) DEFAULT 'O',
	RATE_BRK_S     NUMBER(20,2) DEFAULT 0,
	RATE_BRK_B     NUMBER(20,2) DEFAULT 0,
	RATE_TAX       NUMBER(20,2) DEFAULT 0,
	RATE_ADV       NUMBER(20,2) DEFAULT 0,
	RATE_UB        NUMBER(20,2) DEFAULT 0,
	RATIO_INIT     NUMBER(20,2) DEFAULT 0,
	RATIO_MAIN     NUMBER(20,2) DEFAULT 0,
	RATIO_EXEC     NUMBER(20,2) DEFAULT 0,
	TRFBUYEXT      NUMBER(6) DEFAULT 0,
	TRFBUYAMT      NUMBER(20,2) DEFAULT 0,
	BANKLINK       CHAR(1) DEFAULT 'N',
	BANKACCTNO     VARCHAR2(60) ,
	BANKCODE       VARCHAR2(60) ,
	BOD_NAV        NUMBER(20,2) DEFAULT 0,
	BOD_SEAMT      NUMBER(20,2) DEFAULT 0,
	BOD_SEASS      NUMBER(20,2) DEFAULT 0,
	BOD_ADV        NUMBER(20,2) DEFAULT 0,
	BOD_DEBT       NUMBER(20,2) DEFAULT 0,
	BOD_DEBT_M     NUMBER(20,2) DEFAULT 0,
	BOD_DEBT_T0    NUMBER(20,2) DEFAULT 0,
	BOD_D_MARGIN   NUMBER(20,2) DEFAULT 0,
	BOD_D_MARGIN_UB   NUMBER(20,2) DEFAULT 0,
	BOD_TD         NUMBER(20,2) DEFAULT 0,
	BOD_BALANCE    NUMBER(20,2) DEFAULT 0,
	BOD_INTBAL     NUMBER(20,2) DEFAULT 0,
	BOD_INTACR     NUMBER(20,2) DEFAULT 0,
	BOD_PAYABLE    NUMBER(20,2) DEFAULT 0,
	BOD_CRLIMIT    NUMBER(20,2) DEFAULT 0,
	BOD_T0VALUE    NUMBER(20,2) DEFAULT 0,
	BOD_RCASHT0    NUMBER(20,2) DEFAULT 0,
	BOD_RCASHT1    NUMBER(20,2) DEFAULT 0,
	BOD_RCASHT2    NUMBER(20,2) DEFAULT 0,
	BOD_RCASHT3    NUMBER(20,2) DEFAULT 0,
	BOD_RCASHTN    NUMBER(20,2) DEFAULT 0,
	BOD_SCASHT0    NUMBER(20,2) DEFAULT 0,
	BOD_SCASHT1    NUMBER(20,2) DEFAULT 0,
	BOD_SCASHT2    NUMBER(20,2) DEFAULT 0,
	BOD_SCASHT3    NUMBER(20,2) DEFAULT 0,
	BOD_SCASHTN    NUMBER(20,2) DEFAULT 0,
	CALC_RATIO     NUMBER(20,2) DEFAULT 0,
	CALC_ADVBAL    NUMBER(20,2) DEFAULT 0,
	CALC_SELLMORT  NUMBER(20,2) DEFAULT 0,
	CALC_AVLBAL    NUMBER(20,2) DEFAULT 0,
	CALC_PP0       NUMBER(20,2) DEFAULT 0,
	CALC_NAV       NUMBER(20,2) DEFAULT 0,
	CALC_ASSET     NUMBER(20,2) DEFAULT 0,
	CALC_ODRAMT    NUMBER(20,2) DEFAULT 0,
	CALC_TRFBUYAMT NUMBER(20,2) DEFAULT 0,
	CALC_TRFBUY    NUMBER(20,2) DEFAULT 0,
	LASTCHANGE     TIMESTAMP(6),
	PRIMARY KEY (ACCTNO) );
	--create index IDX_ACCOUNTS_ACCTNO on ACCOUNTS (ACCTNO);
    --create index IDX_ACCOUNTS_CUSTODYCD on ACCOUNTS (CUSTODYCD);
    --create index IDX_ACCOUNTS_GRNAME on ACCOUNTS (GRNAME);
	
create dynamic asynchronous writethrough global cache group g_awt_ORDERS from
	FOPRO.ORDERS (
        ORDERID      VARCHAR2(20),
		TXDATE       DATE,
		NORB         CHAR(1) DEFAULT 'N',
		SESSIONEX    VARCHAR2(6),
		QUOTEID      VARCHAR2(20),
		CONFIRMID    VARCHAR2(25),
		USERID       VARCHAR2(20),
		CUSTODYCD    VARCHAR2(12),
		ACCTNO       VARCHAR2(12),
		SYMBOL       VARCHAR2(15),
		REFORDERID   VARCHAR2(20),
		ROOTORDERID  VARCHAR2(20),
		ORIGINORDERID   VARCHAR2(20) ,
		DEALID       VARCHAR2(5),
		FLAGORDER    VARCHAR2(2),
		SIDE         CHAR(1),
		SUBSIDE      VARCHAR2(6),
		STATUS       CHAR(1) DEFAULT 'P',
		SUBSTATUS    VARCHAR2(6),
		TIME_CREATED TIMESTAMP(6),
		TIME_SEND    TIMESTAMP(6),
		TYPECD       VARCHAR2(6)  DEFAULT 'P',
		SUBTYPECD    VARCHAR2(6),
		RATE_ADV     NUMBER(20,2) DEFAULT 0,
		RATE_BRK     NUMBER(20,2) DEFAULT 0,
		RATE_TAX     NUMBER(20,2) DEFAULT 0,
		RATE_BUY     NUMBER(10,4) DEFAULT 0,
		PRICE_MARGIN NUMBER(20,2) DEFAULT 0,
		PRICE_ASSET  NUMBER(20,2) DEFAULT 0,
		QUOTE_PRICE  NUMBER(20,2) DEFAULT 0,
		QUOTE_QTTY   NUMBER(20) DEFAULT 0,
		EXEC_AMT     NUMBER(20,2) DEFAULT 0,
		EXEC_QTTY    NUMBER(20) DEFAULT 0,
		REMAIN_QTTY  NUMBER(20) DEFAULT 0,
		CANCEL_QTTY  NUMBER(20) DEFAULT 0,
		ADMEND_QTTY  NUMBER(20) DEFAULT 0,
		MORT_QTTY	 NUMBER(20) DEFAULT 0,
		MARKED		 NUMBER(20) DEFAULT 0,
		PRIORITY     VARCHAR2(2) DEFAULT '2', 
		LASTCHANGE   TIMESTAMP(6),
		PRIMARY KEY (ORDERID));
	--create index IDX_ORDERS_ACCTNO on ORDERS (ACCTNO);
    --create index IDX_ORDERS_CUSTODYCD on ORDERS (CUSTODYCD);
    --create index IDX_ORDERS_QUOTEID on ORDERS (QUOTEID);
    --create index IDX_ORDERS_SIDE on ORDERS (SIDE);
    --create index IDX_ORDERS_TYPECD on ORDERS (TYPECD);
    --create index IDX_ORDERS_USERID on ORDERS (USERID);
	
	
	---B13.9: g_awt_PORTFOLIOS
create dynamic asynchronous writethrough global cache group g_awt_PORTFOLIOS from
	FOPRO.PORTFOLIOS (
        ACCTNO     		VARCHAR2(12) ,
		SYMBOL     		VARCHAR2(15) ,
		TRADE      		NUMBER(20) DEFAULT 0,
		MORTGAGE   		NUMBER(20) DEFAULT 0,
		RECEIVING  		NUMBER(20) DEFAULT 0,
		BUYINGQTTY 		NUMBER(20) DEFAULT 0,
		SELLINGQTTY 	NUMBER(20) DEFAULT 0,
		SELLINGQTTYMORT NUMBER(20) DEFAULT 0,
		ASSETQTTY 		NUMBER(20) DEFAULT 0,
		MARKED 			NUMBER(20) DEFAULT 0,
		MARKEDCOM 		NUMBER(20) DEFAULT 0,
		AVGPRICE   		NUMBER(20,4) DEFAULT 0,
		BOD_RT0    		NUMBER(20) DEFAULT 0,
		BOD_RT1    		NUMBER(20) DEFAULT 0,
		BOD_RT2    		NUMBER(20) DEFAULT 0,
		BOD_RT3    		NUMBER(20) DEFAULT 0,
		BOD_RTN    		NUMBER(20) DEFAULT 0,
		BOD_ST0    		NUMBER(20) DEFAULT 0,
		BOD_ST1    		NUMBER(20) DEFAULT 0,
		BOD_ST2    		NUMBER(20) DEFAULT 0,
		BOD_ST3    		NUMBER(20) DEFAULT 0,
		BOD_STN    		NUMBER(20) DEFAULT 0,
		LASTCHANGE 		TIMESTAMP(6),
		--CONSTRAINT fk_acctno FOREIGN KEY (ACCTNO) REFERENCES ACCOUNTS(ACCTNO),
		--CONSTRAINT fk_symbol FOREIGN KEY (SYMBOL) REFERENCES INSTRUMENTS(SYMBOL));
		PRIMARY KEY (ACCTNO,SYMBOL) );
		--create index IDX_PORTFOLIOS on PORTFOLIOS (ACCTNO, SYMBOL);
	
	---B13.9.1: g_awt_PORTFOLIOSEX
create dynamic asynchronous writethrough global cache group g_awt_PORTFOLIOSEX from
	FOPRO.PORTFOLIOSEX (
        ACCTNO                        VARCHAR2(12 BYTE) ,
		SYMBOL                         VARCHAR2(15 BYTE) ,
		BUYINGQTTY                     NUMBER(20,0) DEFAULT 0,
		SELLINGQTTY                    NUMBER(20,0) DEFAULT 0,
		SELLINGQTTYMORT                NUMBER(20,0) DEFAULT 0,
		MARKED                         NUMBER(20,0) DEFAULT 0,
		BOD_RT3                        NUMBER(20,0) DEFAULT 0,
		BOD_ST3                        NUMBER(20,0) DEFAULT 0,
		LASTCHANGE                     TIMESTAMP (6),
		MARKEDCOM                      NUMBER(20,0) DEFAULT 0,
		--CONSTRAINT fk_acctno FOREIGN KEY (ACCTNO) REFERENCES ACCOUNTS(ACCTNO),
		--CONSTRAINT fk_symbol FOREIGN KEY (SYMBOL) REFERENCES INSTRUMENTS(SYMBOL));
		PRIMARY KEY (ACCTNO,SYMBOL) );
		--create index IDX_PORTFOLIOS on PORTFOLIOS (ACCTNO, SYMBOL);
	
create dynamic asynchronous writethrough global cache group g_awt_TRADES from
	FOPRO.TRADES (
        TRADEID    VARCHAR2(20) ,
		ORDERID    VARCHAR2(20) ,
		PRICE      NUMBER(20,2) DEFAULT 0,
		QTTY       NUMBER(20),
		EXECID 	   VARCHAR2(30),
		TIME_EXEC  TIMESTAMP(6),
		STATUS     CHAR(1) DEFAULT 'P',
		LASTCHANGE TIMESTAMP(6),
		PRIMARY KEY (TRADEID) );
		--create index IDX_TRADES on TRADES (ORDERID);
	
	
create dynamic asynchronous writethrough global cache group g_awt_QUOTES from
	FOPRO.QUOTES (
        QUOTEID      VARCHAR2(20) ,
		REQUESTID    VARCHAR2(50),
		CREATEDDT    DATE,
		EXPIREDDT    DATE,
		USERID       VARCHAR2(20), 
		CLASSCD      VARCHAR2(6)  DEFAULT 'DLO',
		SUBCLASS     VARCHAR2(6) ,
		VIA          CHAR(1) DEFAULT 'F',
		STATUS       CHAR(1) DEFAULT 'P',
		SUBSTATUS    VARCHAR2(6) ,
		TIME_QUOTE   TIMESTAMP(6),
		TIME_SEND    TIMESTAMP(6),
		TYPECD       VARCHAR2(6)  DEFAULT 'P',
		SUBTYPECD    VARCHAR2(6) ,
		SIDE         CHAR(1),
		REFQUOTEID   VARCHAR2(20) ,
		SYMBOL       VARCHAR2(15) ,
		QTTY         NUMBER(20) DEFAULT 0,
		QTTY_BASED   NUMBER(20) DEFAULT 0,
		QTTY_DELTA   NUMBER(20) DEFAULT 0,
		QTTY_CANCEL  NUMBER(20) DEFAULT 0,
		QTTY_ADMEND  NUMBER(20) DEFAULT 0,
		DISTRIBUTECD CHAR(1) DEFAULT 'A',
		ACCTNO       VARCHAR2(12) ,
		PRICE        NUMBER(20,2) DEFAULT 0,
		PRICE_RF     NUMBER(20,2) DEFAULT 0,
		PRICE_CE     NUMBER(20,2) DEFAULT 0,
		PRICE_FL     NUMBER(20,2) DEFAULT 0,
		PRICE_DELTA  NUMBER(20,2) DEFAULT 0,
		EXEC_AMT     NUMBER(20,2) DEFAULT 0,
		EXEC_QTTY    NUMBER(20) DEFAULT 0,
		LASTCHANGE   TIMESTAMP(6),
		PRIMARY KEY (REQUESTID)	);
		--create index IDX_QUOTES_ACCTNO on QUOTES (ACCTNO);
		--create index IDX_QUOTES_CLASSCD on QUOTES (CLASSCD);
		--create index IDX_QUOTES_SYMBOL on QUOTES (SYMBOL);
		--create index IDX_QUOTES_USERID on QUOTES (USERID);
		--create index IDX_QUOTES_VIA on QUOTES (VIA);
		
		
create dynamic asynchronous writethrough global cache group g_awt_POOLROOM from
	FOPRO.POOLROOM (
        AUTOID     		NUMBER(20),
		POLICYCD   		VARCHAR2(60) ,    --  khong ap dung duoc trong Oracle
		POLICYTYPE 		CHAR(1) DEFAULT 'C',
		REFSYMBOL  		VARCHAR2(15) ,
		GRANTED    		NUMBER(20) DEFAULT 0,
		INUSED     		NUMBER(20) DEFAULT 0,
		PRIMARY KEY (AUTOID));
		--create index IDX_POOLROOM on POOLROOM(POLICYTYPE, REFSYMBOL);
		
		
	---B13.3: g_awt_BASKETS
create dynamic asynchronous writethrough global cache group g_awt_BASKETS from
	FOPRO.BASKETS (
        BASKETID     VARCHAR2(60),
		SYMBOL       VARCHAR2(15),
		RATE_BUY     NUMBER(10,4) DEFAULT 0,
		RATE_MARGIN  NUMBER(10,4)  DEFAULT 0,
		PRICE_MARGIN NUMBER(20,2) DEFAULT 0,
		PRICE_ASSET  NUMBER(20,2) DEFAULT 0,
		RATE_ASSET 	 NUMBER(10,4)  DEFAULT 0,
		PRIMARY KEY (BASKETID,SYMBOL));

    ----create index IDX_BASKETS_BASKETID on BASKETS (BASKETID);
    ----create index IDX_BASKETS_BASKETSYMBOL on BASKETS(BASKETID, SYMBOL);

	
		
	---B13.4: g_awt_FOUSERS
create dynamic asynchronous writethrough global cache group g_awt_FOUSERS from
	FOPRO.FOUSERS (
        AUTOID   	NUMBER(20),
		TLID     	VARCHAR2(6) ,
		USERNAME 	VARCHAR2(60) ,
		AUTHTYPE 	CHAR(3),
		PWDLOGIN 	VARCHAR2(260) ,
		PWDTRADE 	VARCHAR2(260) ,
		PRIMARY KEY (AUTOID));

		--create index IDX_FOUSERS_USERID on FOUSERS (AUTOID);
		--create index IDX_FOUSERS_USERNAME on FOUSERS (USERNAME);

		
	
	---B13.5: g_awt_PROFILES
create dynamic asynchronous writethrough global cache group g_awt_PROFILES from
	FOPRO.PROFILES (
        AUTOID   	NUMBER(20),
		USERID   	VARCHAR2(20),
		ACCTNO   	VARCHAR2(12),
		ROLETYPE 	CHAR(1) DEFAULT 'O',
		AUTHSTR  	VARCHAR2(60),
		PRIMARY KEY (AUTOID) );

	--create index IDX_PROFILES_USERID on PROFILES (USERID);
	
		
	---B13.6: g_awt_CUSTOMERS
create dynamic asynchronous writethrough global cache group g_awt_CUSTOMERS from
	FOPRO.CUSTOMERS (
		CUSTID    VARCHAR2(10) ,
		CUSTODYCD VARCHAR2(12) ,
		FULLNAME  VARCHAR2(260),
		DOF 	  VARCHAR2(2),
		PRIMARY KEY (CUSTID) );

	--create index IDX_CUSTOMERS_CUSTID on CUSTOMERS (CUSTID);
	--create index IDX_CUSTOMERS_CUSTODYCD on CUSTOMERS(CUSTODYCD);
		
	---B13.7: g_awt_PRODUCTS
create dynamic asynchronous writethrough global cache group g_awt_PRODUCTS from
	FOPRO.PRODUCTS (
        ACTYPE 		VARCHAR2(6) ,
		ACNAME 		VARCHAR2(100) ,
		PRIMARY KEY (ACTYPE));
		
	---B13.8: g_awt_INSTRUMENTS
create dynamic asynchronous writethrough global cache group g_awt_INSTRUMENTS from
	FOPRO.INSTRUMENTS (
        SYMBOL   	VARCHAR2(15),
		SYMBOLNUM   VARCHAR2(10),
		FULLNAME 	VARCHAR2(260),
		CFICODE  	VARCHAR2(10) ,
		EXCHANGE 	VARCHAR2(8) ,
		BOARD    	VARCHAR2(18) ,
		PRICE_CE 	NUMBER(20,2) DEFAULT 0,
		PRICE_FL 	NUMBER(20,2) DEFAULT 0,
		PRICE_RF 	NUMBER(20,2) DEFAULT 0,
		QTTYSUM 	NUMBER(20)  DEFAULT 0,
		FQTTY 		NUMBER(20) DEFAULT 0,
		HALT  		VARCHAR2(1) ,
		PRIMARY KEY (SYMBOL));
		--create index IDX_INSTRUMENTS_SYMBOL on INSTRUMENTS (SYMBOL);
	
create dynamic asynchronous writethrough global cache group g_awt_MARKETINFO from
	FOPRO.MARKETINFO (
        EXCHANGE    VARCHAR2(8),
        INDEXVAL    NUMBER(20,2),
        SESSIONEX   VARCHAR2(6),
        INDEXCHANGE NUMBER(20,2),
        QTTY        NUMBER(20),
        EXEC_AMT    NUMBER(20,2),
    primary key (EXCHANGE));
		
---B16:
create dynamic asynchronous writethrough global cache group g_awt_ALLOCATION from
	FOPRO.ALLOCATION (
        AUTOID     NUMBER(20),
		ORDERID    VARCHAR2(25) ,
		SIDE       CHAR(1),
		SYMBOL     VARCHAR2(20) ,
		ACCTNO     VARCHAR2(20) ,
		PRICE      NUMBER(20,2) DEFAULT 0,
		QTTY       NUMBER(20),
		DOC        CHAR(1),
		POLICYCD   VARCHAR2(20) ,
		POOLID     VARCHAR2(20),
		POOLVAL    NUMBER(20,2),
		ROOMID     VARCHAR2(20),
		ROOMVAL    NUMBER(20,2),
		STATUS     CHAR(1) DEFAULT 'P',
		LASTCHANGE TIMESTAMP(6),
		PRIMARY KEY (AUTOID));
		----create index IDX_ALLOCATION_ACCTNO on ALLOCATION (ACCTNO);
		----create index IDX_ALLOCATION_ORDERID on ALLOCATION (ORDERID);
		----create index IDX_ALLOCATION_POOL on ALLOCATION (POOLID);
		----create index IDX_ALLOCATION_ROOM on ALLOCATION (ROOMID, SYMBOL);
		----create index IDX_ALLOCATION_SYMBOL on ALLOCATION (SYMBOL);

		
		
create dynamic asynchronous writethrough global cache group g_awt_DEFRULES from
	FOPRO.DEFRULES (
        AUTOID   	NUMBER(20),
		REFTYPE  	CHAR(1) DEFAULT 'C',
		REFCODE  	VARCHAR2(26) ,
		RULENAME 	VARCHAR2(60) ,
		REFCVAL  	VARCHAR2(1000) ,
		REFNVAL  	NUMBER(20) DEFAULT 0,
		PRIMARY KEY (AUTOID));

		--create index IDX_DEFRULES_TYPECODE on DEFRULES
		
create dynamic asynchronous writethrough global cache group g_awt_DICERRORS from
	FOPRO.DICERRORS (
		ERRNUM  	NUMBER(10) DEFAULT 0,
        ERRNAME 	VARCHAR2(60 BYTE) ,       
        ERRDESC 	VARCHAR2(260 BYTE) ,
		PRIMARY KEY (ERRNUM));
		

create dynamic asynchronous writethrough global cache group g_awt_STATICDATA from
	FOPRO.STATICDATA (
		AUTOID       NUMBER(20),
		DATACODE     VARCHAR2(20) ,
		DATACAP      VARCHAR2(60) ,
		DATAVAL      VARCHAR2(60) ,
		CDCONTENT    VARCHAR2(100) ,
		EN_CDCONTENT VARCHAR2(100),
		PRIMARY KEY (AUTOID));
		--create index IDX_STATICDATA_DATACODE on STATICDATA (DATACODE);

create dynamic asynchronous writethrough global cache group g_awt_TICKSIZE from
	FOPRO.TICKSIZE (
        AUTOID    	NUMBER(20),
		REFTYPE   	CHAR(1) DEFAULT 'C',
		REFCODE   	VARCHAR2(26) ,
		TICKSIZE  	NUMBER(20) DEFAULT 0,
		FROMPRICE 	NUMBER(20) DEFAULT 0,
		TOPRICE   	NUMBER(20) DEFAULT 0,
		PRIMARY KEY (AUTOID));

		
		
create dynamic asynchronous writethrough global cache group g_awt_TRACKUNIQUE from
	FOPRO.TRACKUNIQUE (
        TYPECD    	VARCHAR2(18) ,
		KEYID     	VARCHAR2(68) ,
		REFID     	VARCHAR2(68) ,
		TRACKTIME 	TIMESTAMP(6),
		TRACKSRC  	VARCHAR2(68),
		PRIMARY KEY (KEYID) );
	
create dynamic asynchronous writethrough global cache group g_awt_TRANSACTIONS from
	FOPRO.TRANSACTIONS (
		AUTOID        NUMBER(20),
		TXID          VARCHAR2(20) ,
		ACTION        VARCHAR2(2) ,
		REFID         VARCHAR2(60) ,
		CONTENT       VARCHAR2(2000) ,
		TIME_CREATED  TIMESTAMP(6),
		TIME_EXECUTED TIMESTAMP(6),
		STATUS        CHAR(1) DEFAULT 'P',
		LASTCHANGE    TIMESTAMP(6),
		PRIMARY KEY (TXID,ACTION));
		
create dynamic asynchronous writethrough global cache group g_awt_SYSCONFIG from
	FOPRO.SYSCONFIG (
		CFGKEY		 VARCHAR2(30),
		CFGVALUE	 VARCHAR2(60),
		DESCRIPTIONS VARCHAR2(200),
		PRIMARY KEY (CFGKEY));
		

		
		
create dynamic asynchronous writethrough global cache group g_awt_MSGERRORS from 
	FOPRO.MSGERRORS (
		CFGKEY	 VARCHAR2(30),
		CFGVALUE	 VARCHAR2(2000),
		STATUS	 VARCHAR2(1),
		DESCRIPTIONS	 VARCHAR2(200),
	PRIMARY KEY (CFGKEY,CFGVALUE));
	
create dynamic asynchronous writethrough global cache group g_awt_CROSSINFO from
	FOPRO.CROSSINFO (
		QUOTEID       VARCHAR2(20),
		CROSSTYPE     VARCHAR2(2) ,
		FIRM      VARCHAR2(6) ,
		TRADERID      VARCHAR2(20) ,
		ACCTNO    VARCHAR2(20) ,
		CUSTODYCD      VARCHAR2(12) ,
		ORDERID VARCHAR2(20),
		TEXT VARCHAR2(20),
	PRIMARY KEY (QUOTEID));

create dynamic asynchronous writethrough global cache group g_awt_ADVORDERS from
	FOPRO.ADVORDERS (
		ORDERID     VARCHAR2(20),
		REFORDERID  VARCHAR2(20) ,
		REFQUOTEID  VARCHAR2(20),
		TXDATE      DATE ,
		STATUS      VARCHAR2(1) ,
		SYMBOL    	VARCHAR2(20) ,
		SIDE 		VARCHAR2(1),
		QTTY 		NUMBER(20) DEFAULT 0,
		PRICE 		NUMBER(20) DEFAULT 0,
		MEMBERID 	VARCHAR2(20) ,
		TEXT 		VARCHAR2(20),
		LASTCHANGE 	TIMESTAMP(6),
		PRIMARY KEY (ORDERID));
	
create dynamic asynchronous writethrough global cache group g_awt_EXCERROR from
	FOPRO.EXCERROR (
		AUTOID        NUMBER(20),
		MSGTYPE       VARCHAR2(4) ,
		STATUS        VARCHAR2(1) DEFAULT 'N',
		REJCODE       VARCHAR2(20) ,
		CONTENT       VARCHAR2(1000) ,
		LASTCHANGE    TIMESTAMP(6),
	PRIMARY KEY (AUTOID));
	
create dynamic asynchronous writethrough global cache group g_awt_WORKINGCALENDAR from
	FOPRO.WORKINGCALENDAR (
        TODAYDATE 	DATE NOT NULL,
        T1DATE    	DATE,
        T2DATE    	DATE,
        T3DATE    	DATE,
        HOLIDAY   	VARCHAR2(1) DEFAULT 'N',
    primary key (TODAYDATE));
	
create dynamic asynchronous writethrough global cache group g_awt_OWNPOOLROOM from
	FOPRO.OWNPOOLROOM (
        PRID 	  VARCHAR2(20),
        ACCTNO    VARCHAR2(12),
		POLICYTYPE 		CHAR(1),
		REFSYMBOL VARCHAR2(15) ,
		INUSED   NUMBER(20) DEFAULT 0,
    primary key (PRID,ACCTNO,REFSYMBOL));

create dynamic asynchronous writethrough global cache group g_awt_BANKACCORDERS from
	FOPRO.BANKACCORDERS (
		QUOTEID      VARCHAR2(20) ,
		ACCTNO       VARCHAR2(12) ,
		AMOUNT       NUMBER(20,2) DEFAULT 0,
		STATUS       CHAR(1) DEFAULT 'P',
		LASTCHANGE   TIMESTAMP(6),
	PRIMARY KEY (QUOTEID));
	
	--dung.bui them cache group, date 13/12/2015
create dynamic asynchronous writethrough global cache group g_awt_GW_MSG_LOGS from
	FOPRO.GW_MSG_LOGS (
		AUTOID NUMBER(20,0),
		GW_DATE TIMESTAMP(6),
		EXCHANGE VARCHAR2(10),
		XMLCONTENT VARCHAR2(4000), 
	PRIMARY KEY(AUTOID));
	
create dynamic asynchronous writethrough global cache group g_awt_HFT_MSG_LOGS from
	FOPRO.HFT_MSG_LOGS (
		ORDERID VARCHAR2(20),
		EXCHANGE VARCHAR2(10),
		STATUS VARCHAR2(3) DEFAULT 'S',
		XMLCONTENT VARCHAR2(4000),
		HFT_DATE TIMESTAMP(6),
	PRIMARY KEY(ORDERID));
	
create dynamic asynchronous writethrough global cache group g_awt_TRADING_EXCEPTION from
	FOPRO.TRADING_EXCEPTION (
		MSGID VARCHAR2(20),
		MSGSEQNUM VARCHAR2(20),
		ORDSTATUS VARCHAR2(5),
		CLORDID VARCHAR2(20),
		ORIGCLORDID VARCHAR2(20),
		SECONDARYCLORDID VARCHAR2(20),
		ORDERID VARCHAR2(25),
		TRANSACTTIME VARCHAR2(20),
		LASTQTY	NUMBER,
		LASTPX NUMBER,
		EXECID VARCHAR2(20),
		SIDE VARCHAR2(1),
		SYMBOL VARCHAR2(15),
		CONTRA_CLORDID VARCHAR2(20),
		CREATE_TIME	TIMESTAMP(6),
	PRIMARY KEY(MSGID));
		
create dynamic asynchronous writethrough global cache group g_awt_TRADING_EXCEPTION_LOG from
	FOPRO.TRADING_EXCEPTION_LOG (
		MSGID				VARCHAR2(20),
		MSGSEQNUM 			VARCHAR2(20),
		ORDSTATUS 			VARCHAR2(5),
		CLORDID 			VARCHAR2(20),
		ORIGCLORDID 		VARCHAR2(20),
		SECONDARYCLORDID 	VARCHAR2(20),
		ORDERID 			VARCHAR2(20),
		TRANSACTTIME 		VARCHAR2(20),
		LASTQTY 			NUMBER,
		LASTPX 				NUMBER,
		EXECID 				VARCHAR2(20),
		SIDE 				VARCHAR2(1),
		SYMBOL 				VARCHAR2(15),
		CONTRA_CLORDID		VARCHAR2(20),
		CREATE_TIME			TIMESTAMP,
		ERR_CODE 			VARCHAR2(15),
		STATUS				CHAR(1),
		PRIMARY KEY(MSGID));
	--end
	
	
