--tao cac sequence tren timesten
DROP SEQUENCE SEQ_TRANSACTIONS;
CREATE SEQUENCE SEQ_TRANSACTIONS
	 START WITH     1
	 INCREMENT BY   1
	 MAXVALUE       9999999999
	 NOCACHE
	 CYCLE;
	 
DROP SEQUENCE SEQ_POOLROOM;
CREATE SEQUENCE SEQ_POOLROOM
	START WITH     1
	MAXVALUE       9999999999
	INCREMENT BY   1
	NOCACHE
	CYCLE;

DROP SEQUENCE SEQ_COMMON;
CREATE SEQUENCE SEQ_COMMON
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;

DROP SEQUENCE SEQ_DEALID;
CREATE SEQUENCE SEQ_DEALID
	 START WITH     50001
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;
	 
DROP SEQUENCE SEQ_BASKETS;
CREATE SEQUENCE SEQ_BASKETS
	START WITH     1
	MAXVALUE       9999999999
	INCREMENT BY   1
	NOCACHE
	CYCLE;
	
DROP SEQUENCE SEQ_DEFRULES;
CREATE SEQUENCE SEQ_DEFRULES
	START WITH     1
	MAXVALUE       9999999999
	INCREMENT BY   1
	NOCACHE
	CYCLE;
	 
	 
--DROP SEQUENCE SEQ_FOUSERS;
	--CREATE SEQUENCE SEQ_FOUSERS
	-- START WITH     1
	-- MAXVALUE       9999999999
	--INCREMENT BY   1
	 --NOCACHE
	 --CYCLE;
	 
		
--DROP SEQUENCE SEQ_PROFILES;
--CREATE SEQUENCE SEQ_PROFILES
	-- START WITH     1
	 --MAXVALUE       9999999999
	 --INCREMENT BY   1
	 --NOCACHE
	 --CYCLE;
	 	
DROP SEQUENCE SEQ_ALLOCATION;
CREATE SEQUENCE SEQ_ALLOCATION
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;
	 
DROP SEQUENCE SEQ_ORDERS;
CREATE SEQUENCE SEQ_ORDERS
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;
	 
DROP SEQUENCE SEQ_TRADING;
CREATE SEQUENCE SEQ_TRADING
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;
	 
DROP SEQUENCE SEQ_QUOTES;
CREATE SEQUENCE SEQ_QUOTES
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;
	 
DROP SEQUENCE SEQ_ROOT_ORDERID;
CREATE SEQUENCE SEQ_ROOT_ORDERID
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;
	
	 
 DROP SEQUENCE SEQ_EXCERROR;
 CREATE SEQUENCE SEQ_EXCERROR
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;
	 
DROP SEQUENCE SEQ_HNX_ORDERID;
CREATE SEQUENCE SEQ_HNX_ORDERID
	 START WITH     1
	 MAXVALUE       9999999999
	 INCREMENT BY   1
	 NOCACHE
	 CYCLE;

DROP SEQUENCE SEQ_ttlogs;
CREATE SEQUENCE SEQ_ttlogs
	START WITH     1
	MAXVALUE       9999999999
	INCREMENT BY   1
	NOCACHE
	CYCLE;

DROP SEQUENCE SEQ_GW_MSG_LOGS;
CREATE SEQUENCE SEQ_GW_MSG_LOGS
	START WITH     1
	MAXVALUE       9999999999
	INCREMENT BY   1
	NOCACHE
	CYCLE;

DROP SEQUENCE SEQ_MSG_832;
CREATE SEQUENCE SEQ_MSG_832
	INCREMENT BY 1
	MAXVALUE 1000000000
	CYCLE
	START WITH 1;
	 
