CREATE INDEX "HOSTKBSVT"."TLLOGFLDALL_TXNUM_TXDATE" ON "HOSTKBSVT"."TLLOGFLDALL" ("TXDATE", "TXNUM");
CREATE INDEX "HOSTKBSVT"."IDX_CITRAN_GEN_ACCTNO" ON "HOSTKBSVT"."CITRAN_GEN" ("ACCTNO");
CREATE INDEX "HOSTKBSVT"."IDX_CITRAN_GEN_CUSTODYCD" ON "HOSTKBSVT"."CITRAN_GEN" ("CUSTODYCD");
CREATE INDEX "HOSTKBSVT"."IDX_CITRAN_GEN_CUSTID" ON "HOSTKBSVT"."CITRAN_GEN" ("CUSTID");

CREATE UNIQUE INDEX "HOSTKBSVT"."IDX_CITRAN_GEN_AUTOID" ON "HOSTKBSVT"."CITRAN_GEN" ("AUTOID");

CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_AUTOID" ON "HOSTKBSVT"."SETRAN_GEN" ("AUTOID");
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_CODEID" ON "HOSTKBSVT"."SETRAN_GEN" ("CODEID");
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_SYMBOL" ON "HOSTKBSVT"."SETRAN_GEN" ("SYMBOL");
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_AFACCTNO" ON "HOSTKBSVT"."SETRAN_GEN" ("AFACCTNO");
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_ACCTNO" ON "HOSTKBSVT"."SETRAN_GEN" ("ACCTNO") ;
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_CUSTODYCD" ON "HOSTKBSVT"."SETRAN_GEN" ("CUSTODYCD");
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_CUSTID" ON "HOSTKBSVT"."SETRAN_GEN" ("CUSTID") ;
CREATE INDEX "HOSTKBSVT"."TLLOGALL_TXD_TLTXCD_IDX" ON "HOSTKBSVT"."TLLOGALL" ("TXDATE", "TLTXCD") ;
CREATE INDEX "HOSTKBSVT"."TLLOGALL_TXNUM_TXDATE_IDX" ON "HOSTKBSVT"."TLLOGALL" ("TXNUM", "TXDATE") ;
CREATE INDEX "HOSTKBSVT"."CITRANA_TXCD_IDX" ON "HOSTKBSVT"."CITRANA" ("TXCD") ;
CREATE INDEX "HOSTKBSVT"."CITRANA_ACCTNO_IDX" ON "HOSTKBSVT"."CITRANA" ("ACCTNO") ;
CREATE INDEX "HOSTKBSVT"."SETRANA_TXNUM_TXDATE_IDX" ON "HOSTKBSVT"."SETRANA" ("TXNUM", "TXDATE");
CREATE INDEX "HOSTKBSVT"."SETRANA_ACCTNO_IDX" ON "HOSTKBSVT"."SETRANA" ("ACCTNO") ;
CREATE INDEX "HOSTKBSVT"."IODHIST_ORGORDERID_IDX" ON "HOSTKBSVT"."IODHIST" ("ORGORDERID");
CREATE INDEX "HOSTKBSVT"."IODHIST_TXDATE" ON "HOSTKBSVT"."IODHIST" ("TXDATE");
CREATE INDEX "HOSTKBSVT"."MAINTAIN_LOG_TABLE_COLUMN_IDX" ON "HOSTKBSVT"."MAINTAIN_LOG" ("TABLE_NAME", "COLUMN_NAME");

CREATE UNIQUE INDEX "HOSTKBSVT"."CIINTTRAN_PK" ON "HOSTKBSVT"."CIINTTRAN" ("AUTOID") ;

CREATE INDEX "HOSTKBSVT"."IDX_CITRAN_GEN_BUSDATE" ON "HOSTKBSVT"."CITRAN_GEN" ("BUSDATE") ;
CREATE INDEX "HOSTKBSVT"."SEDEPOBAL_TXDATE_IDX" ON "HOSTKBSVT"."SEDEPOBAL" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."LNSCHDLOGHIST_TXDATE_IDX" ON "HOSTKBSVT"."LNSCHDLOGHIST" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."LNSCHDLOGHIST_AUTOID_IDX" ON "HOSTKBSVT"."LNSCHDLOGHIST" ("AUTOID") ;
CREATE INDEX "HOSTKBSVT"."MAINTAIN_LOG_RECORD_KEY_IDX" ON "HOSTKBSVT"."MAINTAIN_LOG" ("TABLE_NAME", "RECORD_KEY") ;
CREATE INDEX "HOSTKBSVT"."CI1018_LOG_TXDATE_IDX" ON "HOSTKBSVT"."CI1018_LOG" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."CI1018_LOG_BUSDATE_IDX" ON "HOSTKBSVT"."CI1018_LOG" ("BUSDATE") ;
CREATE INDEX "HOSTKBSVT"."CI1018_LOG_TLTXCD_FILTER_IDX" ON "HOSTKBSVT"."CI1018_LOG" ("TLTXCD_FILTER") ;
CREATE INDEX "HOSTKBSVT"."CI1018_LOG_CUSTODYCD_IDX" ON "HOSTKBSVT"."CI1018_LOG" ("CUSTODYCD") ;
CREATE INDEX "HOSTKBSVT"."MR5005_LOG_TXDATE_IDX" ON "HOSTKBSVT"."MR5005_LOG" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."LOG_SA0015_TXDATE_IDX" ON "HOSTKBSVT"."LOG_SA0015" ("TXDATE") ;

CREATE UNIQUE INDEX "HOSTKBSVT"."IODQUEUE_UK" ON "HOSTKBSVT"."IODQUEUE" ("TXDATE", "BORS", "CONFIRM_NO", "SYMBOL") ;

CREATE INDEX "HOSTKBSVT"."STSCHDHIST_AFACCTNO_IDX" ON "HOSTKBSVT"."STSCHDHIST" ("AFACCTNO") ;
CREATE INDEX "HOSTKBSVT"."STSCHDHIST_AUTOID_IDX" ON "HOSTKBSVT"."STSCHDHIST" ("AUTOID") ;
CREATE INDEX "HOSTKBSVT"."IDX_ODTRANA_TXDATE" ON "HOSTKBSVT"."ODTRANA" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."IDX_MAINTAIN_LOG_MAKER_DT" ON "HOSTKBSVT"."MAINTAIN_LOG" ("MAKER_DT");
CREATE INDEX "HOSTKBSVT"."IDX_AFPRALLOCHIST_TXDATE" ON "HOSTKBSVT"."AFPRALLOCHIST" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."STSCHDHIST_CLEARDATE_IDX" ON "HOSTKBSVT"."STSCHDHIST" ("CLEARDATE");
CREATE INDEX "HOSTKBSVT"."T_FO_ROOM_ALLOCATION_HIST_IDX" ON "HOSTKBSVT"."T_FO_ROOM_ALLOCATION_HIST" ("ACCTNO") ;
CREATE INDEX "HOSTKBSVT"."ODMASTDTL_TXDATE_IDX" ON "HOSTKBSVT"."ODMASTDTL" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."ODMASTDTL_AFACCTNO_IDX" ON "HOSTKBSVT"."ODMASTDTL" ("AFACCTNO") ;
CREATE INDEX "HOSTKBSVT"."ODMASTDTL_AFACCTNO_CODEID_IDX" ON "HOSTKBSVT"."ODMASTDTL" ("AFACCTNO", "CODEID") ;
CREATE INDEX "HOSTKBSVT"."ODMASTDTL_CODEID_IDX" ON "HOSTKBSVT"."ODMASTDTL" ("CODEID") ;
CREATE INDEX "HOSTKBSVT"."IODHIST_CONFIRM_NO_IDX" ON "HOSTKBSVT"."IODHIST" ("CONFIRM_NO") ; 
CREATE INDEX "HOSTKBSVT"."IDX_CFNAVLOG_CUSTID" ON "HOSTKBSVT"."CFNAVLOG" ("CUSTID") ;
CREATE INDEX "HOSTKBSVT"."IDX_CFNAVLOG_TXDATE" ON "HOSTKBSVT"."CFNAVLOG" ("TXDATE") ;
CREATE INDEX "HOSTKBSVT"."IDX_LO1" ON "HOSTKBSVT"."LOG_SA0015" ("TXDATE", "AFACCTNO") ;
CREATE INDEX "HOSTKBSVT"."IDX_WEC_LOGTEMP1" ON "HOSTKBSVT"."LOG_SA0015" ("TXDATE", "AFACCTNO", "NAVAMT_ED") ;
CREATE INDEX "HOSTKBSVT"."IND_SETRAN_GEN_DELTD" ON "HOSTKBSVT"."SETRAN_GEN" ("DELTD") ;
CREATE INDEX "HOSTKBSVT"."IND_SETRAN_GEN_IND1" ON "HOSTKBSVT"."SETRAN_GEN" ("ACCTNO", "FIELD", "TLTXCD", "TXDATE") ;
CREATE INDEX "HOSTKBSVT"."IND_SETRAN_GEN_IND2" ON "HOSTKBSVT"."SETRAN_GEN" ("TLTXCD", "TXDATE") ;
CREATE INDEX "HOSTKBSVT"."WEC_ODMHIST_IDX" ON "HOSTKBSVT"."ODMASTHIST" ("CODEID") ;
CREATE INDEX "HOSTKBSVT"."WEC_IODHIST_IDX" ON "HOSTKBSVT"."IODHIST" ("CODEID") ;
CREATE INDEX "HOSTKBSVT"."IDX_CITRAN_GEN_TXDATE_TXNUM" ON "HOSTKBSVT"."CITRAN_GEN" ("TXDATE" DESC, "TXNUM" DESC) ;
CREATE INDEX "HOSTKBSVT"."IDX_CITRAN_GEN_TXDATE" ON "HOSTKBSVT"."CITRAN_GEN" ("TXDATE" DESC) ;
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_BUSDATE" ON "HOSTKBSVT"."SETRAN_GEN" ("BUSDATE" DESC) ;
CREATE INDEX "HOSTKBSVT"."IDX_SETRAN_GEN_TXDATE_TXNUM" ON "HOSTKBSVT"."SETRAN_GEN" ("TXDATE" DESC, "TXNUM" DESC) ;
CREATE INDEX "HOSTKBSVT"."TLLOGALL_BUSDATE_IDX" ON "HOSTKBSVT"."TLLOGALL" ("BUSDATE" DESC) ;
CREATE INDEX "HOSTKBSVT"."TLLOGALL_TXDATE_IDX" ON "HOSTKBSVT"."TLLOGALL" ("TXDATE" DESC) ;
CREATE INDEX "HOSTKBSVT"."CITRANA_TXDATE_IDX" ON "HOSTKBSVT"."CITRANA" ("TXDATE" DESC) ;
CREATE INDEX "HOSTKBSVT"."CITRANA_TXNUM_TXDATE_IDX" ON "HOSTKBSVT"."CITRANA" ("TXNUM" DESC, "TXDATE" DESC) ;
CREATE INDEX "HOSTKBSVT"."ODMASTDTL_ORDERID_IDX" ON "HOSTKBSVT"."ODMASTDTL" ("ORDERID" DESC) ;

ALTER TABLE "HOSTKBSVT"."CIINTTRAN" ADD CONSTRAINT "CIINTTRAN_PK" PRIMARY KEY ("AUTOID") ;
ALTER TABLE "HOSTKBSVT"."TRANSLOG" ADD PRIMARY KEY ("ID") ;
ALTER TABLE "HOSTKBSVT"."TRANSLOG" ADD UNIQUE ("SEQUENCEMSG", "TRADINGDATE") ;
ALTER TABLE "HOSTKBSVT"."IODQUEUE" ADD CONSTRAINT "IODQUEUE_UK" UNIQUE ("TXDATE", "BORS", "CONFIRM_NO", "SYMBOL");












