--
--
/
truncate table HOSTMSBST.T_FO_LOGCALLWS_HIST;
commit;
/
CREATE TABLE tllogall_n AS SELECT * FROM tllogall WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table tllogall;
INSERT INTO tllogall SELECT * FROM tllogall_n;
commit;
/
CREATE TABLE CITRAN_GEN_n AS SELECT * FROM CITRAN_GEN WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table CITRAN_GEN;
INSERT INTO CITRAN_GEN SELECT * FROM CITRAN_GEN_n;
commit;
/
CREATE TABLE CITRANA_n AS SELECT * FROM CITRANA WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table CITRANA;
INSERT INTO CITRANA SELECT * FROM CITRANA_n;
commit;
/
CREATE TABLE SETRAN_GEN_n AS SELECT * FROM SETRAN_GEN WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table SETRAN_GEN;
INSERT INTO SETRAN_GEN SELECT * FROM SETRAN_GEN_n;
commit;
/
CREATE TABLE LOG_MR4000_n AS SELECT * FROM LOG_MR4000 WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table LOG_MR4000;
INSERT INTO LOG_MR4000 SELECT * FROM LOG_MR4000_n;
commit;
/
CREATE TABLE ODMASTHIST_n AS SELECT * FROM ODMASTHIST WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table ODMASTHIST;
INSERT INTO ODMASTHIST SELECT * FROM ODMASTHIST_n;
commit;
/
CREATE TABLE ODTRANA_n AS SELECT * FROM ODTRANA WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table ODTRANA;
INSERT INTO ODTRANA SELECT * FROM ODTRANA_n;
commit;
/
CREATE TABLE FOMASTHIST_n AS SELECT * FROM FOMASTHIST WHERE to_date(substr(acctno,1,10),'dd/mm/rrrr') >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table FOMASTHIST;
INSERT INTO FOMASTHIST SELECT * FROM FOMASTHIST_n;
commit;
/
--truncate table HOSTMSBST.MAINTAIN_LOG;
commit;
/
CREATE TABLE SETRANA_n AS SELECT * FROM SETRANA WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table SETRANA;
INSERT INTO SETRANA SELECT * FROM SETRANA_n;
commit;
/
CREATE TABLE CI1018_LOG_n AS SELECT * FROM CI1018_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table CI1018_LOG;
INSERT INTO CI1018_LOG SELECT * FROM CI1018_LOG_n;
commit;
/
CREATE TABLE SEDEPOBAL_n AS SELECT * FROM SEDEPOBAL WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table SEDEPOBAL;
INSERT INTO SEDEPOBAL SELECT * FROM SEDEPOBAL_n;
commit;
/
drop table LOG_SA0015_062020;
commit;
/
CREATE TABLE LOG_SA0015_n AS SELECT * FROM LOG_SA0015 WHERE txdate >= TO_DATE('01/01/2019','dd/mm/rrrr');
truncate table LOG_SA0015;
INSERT INTO LOG_SA0015 SELECT * FROM LOG_SA0015_n;
commit;
/
--CREATE TABLE AFMRSERISKHIST_n AS SELECT * FROM AFMRSERISKHIST WHERE to_date(substr(backupdt,1,10),'dd/mm/rrrr') >= TO_DATE('01/01/2021','dd/mm/rrrr');
truncate table AFMRSERISKHIST;
--INSERT INTO AFMRSERISKHIST SELECT * FROM AFMRSERISKHIST_n;
commit;
/
--CREATE TABLE AFSERISKHIST_n AS SELECT * FROM AFSERISKHIST WHERE to_date(substr(backupdt,1,10),'dd/mm/rrrr') >= TO_DATE('01/01/2021','dd/mm/rrrr');
truncate table AFSERISKHIST;
--INSERT INTO AFSERISKHIST SELECT * FROM AFSERISKHIST_n;
commit;
/
CREATE TABLE MR5005_LOG_n AS SELECT * FROM MR5005_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table MR5005_LOG;
INSERT INTO MR5005_LOG SELECT * FROM MR5005_LOG_n;
commit;
/
CREATE TABLE ODMASTDTL_n AS SELECT * FROM ODMASTDTL WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table ODMASTDTL;
INSERT INTO ODMASTDTL SELECT * FROM ODMASTDTL_n;
commit;
/
CREATE TABLE AFSE_INFO_LOG_n AS SELECT * FROM AFSE_INFO_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table AFSE_INFO_LOG;
INSERT INTO AFSE_INFO_LOG SELECT * FROM AFSE_INFO_LOG_n;
commit;
/
CREATE TABLE ODQUEUEALL_n AS SELECT * FROM ODQUEUEALL WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table ODQUEUEALL;
INSERT INTO ODQUEUEALL SELECT * FROM ODQUEUEALL_n;
commit;
/
truncate table HOSTMSBST.T_FO_PROFILES_HIST;
commit;
/
truncate table HOSTMSBST.SECURITIES_INFO_HIST;
commit;
/
CREATE TABLE SECURITIES_INFO_LOG_n AS SELECT * FROM SECURITIES_INFO_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table SECURITIES_INFO_LOG;
INSERT INTO SECURITIES_INFO_LOG SELECT * FROM SECURITIES_INFO_LOG_n;
commit;
/
CREATE TABLE LNINTTRAN_n AS SELECT * FROM LNINTTRAN WHERE todate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table LNINTTRAN;
INSERT INTO LNINTTRAN SELECT * FROM LNINTTRAN_n;
commit;
/
CREATE TABLE LNINTTRAN_n AS SELECT * FROM LNINTTRAN WHERE todate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table LNINTTRAN;
INSERT INTO LNINTTRAN SELECT * FROM LNINTTRAN_n;
commit;
/
CREATE TABLE CIINTTRAN_n AS SELECT * FROM CIINTTRAN WHERE todate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table CIINTTRAN;
INSERT INTO CIINTTRAN SELECT * FROM CIINTTRAN_n;
commit;
/
--CREATE TABLE EVENTSLOG_n AS SELECT * FROM EVENTSLOG WHERE etime >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table EVENTSLOG;
--INSERT INTO EVENTSLOG SELECT * FROM EVENTSLOG_n;
commit;
/
CREATE TABLE AFPRALLOC_BF_BATCH_n AS SELECT * FROM AFPRALLOC_BF_BATCH WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table AFPRALLOC_BF_BATCH;
INSERT INTO AFPRALLOC_BF_BATCH SELECT * FROM AFPRALLOC_BF_BATCH_n;
commit;
/
CREATE TABLE AFPRALLOCHIST_n AS SELECT * FROM AFPRALLOCHIST WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table AFPRALLOCHIST;
INSERT INTO AFPRALLOCHIST SELECT * FROM AFPRALLOCHIST_n;
commit;
/
CREATE TABLE MR9000_LOGHIST_n AS SELECT * FROM MR9000_LOGHIST WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table MR9000_LOGHIST;
INSERT INTO MR9000_LOGHIST SELECT * FROM MR9000_LOGHIST_n;
commit;
/
truncate table HOSTMSBST.T_FO_PORTFOLIOS_HIST;
commit;
/
--CREATE TABLE ODCHANGING_TRIGGER_LOG_n AS SELECT * FROM ODCHANGING_TRIGGER_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table ODCHANGING_TRIGGER_LOG;
--INSERT INTO ODCHANGING_TRIGGER_LOG SELECT * FROM ODCHANGING_TRIGGER_LOG_n;
commit;
/
truncate table HOSTMSBST.T_FO_INDAY_DEFRULES_HIST;
/
CREATE TABLE LNSCHDLOGHIST_n AS SELECT * FROM LNSCHDLOGHIST WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table LNSCHDLOGHIST;
INSERT INTO LNSCHDLOGHIST SELECT * FROM LNSCHDLOGHIST_n;
commit;
/
CREATE TABLE LNTRANA_n AS SELECT * FROM LNTRANA WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table LNTRANA;
INSERT INTO LNTRANA SELECT * FROM LNTRANA_n;
commit;
/
truncate table HOSTMSBST.T_FO_DEFRULES_HIST;
commit;
/
CREATE TABLE TBL_MR3007_LOG_n AS SELECT * FROM TBL_MR3007_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table TBL_MR3007_LOG;
INSERT INTO TBL_MR3007_LOG SELECT * FROM TBL_MR3007_LOG_n;
commit;
/
truncate table HOSTMSBST.T_FO_BASKET_HIST;
commit;
/
DECLARE
 po_t dbms_aqadm.aq$_purge_options_t;
begin
  dbms_aqadm.purge_queue_table('TXAQS_FLEX2FO_TABLE', NULL, po_t);
  commit;
end;
/*CREATE TABLE TXAQS_FLEX2FO_TABLE_n AS SELECT * FROM TXAQS_FLEX2FO_TABLE WHERE enq_time >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table TXAQS_FLEX2FO_TABLE;
INSERT INTO TXAQS_FLEX2FO_TABLE SELECT * FROM TXAQS_FLEX2FO_TABLE_n;
commit;*/
/
truncate table HOSTMSBST.LOG_ERR;
commit;
/
CREATE TABLE TBL_PR0003_LOG_n AS SELECT * FROM TBL_PR0003_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table TBL_PR0003_LOG;
INSERT INTO TBL_PR0003_LOG SELECT * FROM TBL_PR0003_LOG_n;
commit;
/
truncate table HOSTMSBST.T_FO_CUSTOMER_HIST;
commit;
/
truncate table HOSTMSBST.CUSTOMERLIST_HIST;
commit
/
CREATE TABLE TLLOGFLDALL_n AS SELECT * FROM TLLOGFLDALL WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table TLLOGFLDALL;
INSERT INTO TLLOGFLDALL SELECT * FROM TLLOGFLDALL_n;
commit;
/
drop table HOSTMSBST.OTRIGHTDTL_BACKUP;
commit;
/
truncate table HOSTMSBST.T_FO_INSTRUMENTS_HIST;
truncate table HOSTMSBST.T_FO_ACCOUNT_HIST;
commit;
/
CREATE TABLE AFLN_INFO_LOG_n AS SELECT * FROM AFLN_INFO_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table AFLN_INFO_LOG;
INSERT INTO AFLN_INFO_LOG SELECT * FROM AFLN_INFO_LOG_n;
commit;
/
CREATE TABLE CRBTXREQ_n AS SELECT * FROM CRBTXREQ WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table CRBTXREQ;
INSERT INTO CRBTXREQ SELECT * FROM CRBTXREQ_n;
commit;
/
CREATE TABLE CFNAVLOG_n AS SELECT * FROM CFNAVLOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table CFNAVLOG;
INSERT INTO CFNAVLOG SELECT * FROM CFNAVLOG_n;
commit;
/
CREATE TABLE CRBTXREQDTL_n AS SELECT * FROM CRBTXREQDTL r
WHERE not exists (select 1 from CRBTXREQ where reqid = r.reqid);
truncate table CRBTXREQDTL;
INSERT INTO CRBTXREQDTL SELECT * FROM CRBTXREQDTL_n;
commit;
/
CREATE TABLE MR3009_LOGALL_n AS SELECT * FROM MR3009_LOGALL WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table MR3009_LOGALL;
INSERT INTO MR3009_LOGALL SELECT * FROM MR3009_LOGALL_n;
commit;
/
CREATE TABLE PRTRANA_n AS SELECT * FROM PRTRANA WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table PRTRANA;
INSERT INTO PRTRANA SELECT * FROM PRTRANA_n;
commit;
/
CREATE TABLE GLDEALPAY_n AS SELECT * FROM GLDEALPAY WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table GLDEALPAY;
INSERT INTO GLDEALPAY SELECT * FROM GLDEALPAY_n;
commit;
/
truncate table HOSTMSBST.SMSBEGINDAY_HIST;
commit;
/
CREATE TABLE ADSCHDDTL_n AS SELECT * FROM ADSCHDDTL WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table ADSCHDDTL;
INSERT INTO ADSCHDDTL SELECT * FROM ADSCHDDTL_n;
commit;
/
truncate table HOSTMSBST.MR5005_LOG_BK1;
commit;
/
CREATE TABLE SECOSTPRICE_n AS SELECT * FROM SECOSTPRICE WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table SECOSTPRICE;
INSERT INTO SECOSTPRICE SELECT * FROM SECOSTPRICE_n;
commit;
/
CREATE TABLE REFPRICE_LOG_n AS SELECT * FROM REFPRICE_LOG WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table REFPRICE_LOG;
INSERT INTO REFPRICE_LOG SELECT * FROM REFPRICE_LOG_n;
commit;
/
truncate table HOSTMSBST.EMAILPOPLOG;
commit;
/
CREATE TABLE RETRANA_n AS SELECT * FROM RETRANA WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table RETRANA;
INSERT INTO RETRANA SELECT * FROM RETRANA_n;
commit;
/
CREATE TABLE LOG_PR0004_n AS SELECT * FROM LOG_PR0004 WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table LOG_PR0004;
INSERT INTO LOG_PR0004 SELECT * FROM LOG_PR0004_n;
commit;
/
CREATE TABLE GL_EXP_TRAN_n AS SELECT * FROM GL_EXP_TRAN WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table GL_EXP_TRAN;
INSERT INTO GL_EXP_TRAN SELECT * FROM GL_EXP_TRAN_n;
commit;
/
truncate table HOSTMSBST.SENDMSGLOG;
drop table HOSTMSBST.AFMAST_BK;
commit;
/
CREATE TABLE AFTRANA_n AS SELECT * FROM AFTRANA WHERE txdate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table AFTRANA;
INSERT INTO AFTRANA SELECT * FROM AFTRANA_n;
commit;
/
CREATE TABLE REINTTRANA_n AS SELECT * FROM REINTTRANA WHERE todate >= TO_DATE('01/01/2018','dd/mm/rrrr');
truncate table REINTTRANA;
INSERT INTO REINTTRANA SELECT * FROM REINTTRANA_n;
commit;
/
truncate table HOSTMSBST.T_FO_TMP_BASKET_HIST;
truncate table HOSTMSBST.T_FO_TMP_AFSERULE;
truncate table HOSTMSBST.TBLCASHDEPOSITHIST;
commit;
/
truncate table HOSTMSBST.T_FO_POOLROOM_HIST;
truncate table HOSTMSBST.T_FO_PRODUCTS_HIST;
truncate table HOSTMSBST.T_FO_EVENT_HIST;
truncate table HOSTMSBST.LOG_NOTIFY_EVENT_HIST;
truncate table HOSTMSBST.T_FO_TMP_ODFEE_HIST;
commit;
/
truncate table HOSTMSBST.MSGRECEIVETEMP_HIST;
truncate table HOSTMSBST.T_FO_PROFILES;
truncate table HOSTMSBST.T_FO_INDAY_BASKET_HIST;
drop table HOSTMSBST.CFOTHERACC_0505;
drop table HOSTMSBST.CFOTHERACC_2904;
drop table HOSTMSBST.CFOTHERACC_2404;
drop table HOSTMSBST.USERAFLIMIT_20200422;
drop table HOSTMSBST.BANK_BRANCH_INFO_2404;
drop table HOSTMSBST.EMAILLOG_BK;
drop table HOSTMSBST.OOD_BK1903_1;
drop table HOSTMSBST.OOD_BK1903;
drop table HOSTMSBST.AFPRALLOC_BK_1605;
truncate table HOSTMSBST.T_FO_TMP_INSTRUMENTS_HIST;
truncate table HOSTMSBST.T_FO_OWNPOOLROOM_HIST;
drop table HOSTMSBST.T_FO_REICEIVEORDER_BK1903;
drop table HOSTMSBST.LNSCHD_20201019;
drop table HOSTMSBST.AFIDTYPE_20200110;
drop table HOSTMSBST.AFIDTYPE_20200110_1;
drop table HOSTMSBST.DEFERROR_150916;
drop table HOSTMSBST.CONFIRMODRS_BK;
truncate table HOSTMSBST.TBLCFCHGBRIDHIST;
truncate table HOSTMSBST.ODBRKFEEHIST;
drop table HOSTMSBST.LNSCHD_CMP_LNSCHDLOG_20201019;
drop table HOSTMSBST.NEWFO_ORDERMAP_BK;
truncate table HOSTMSBST.AFSEBASKETHIST;
truncate table HOSTMSBST.AFTXMAPHIST;
truncate table HOSTMSBST.ALL_DAYPRICE_HIST;
truncate table HOSTMSBST.BORQSLOGDTLHIST;
truncate table HOSTMSBST.BORQSLOGHIST;
truncate table HOSTMSBST.DFBASKETHIST;
truncate table HOSTMSBST.DFMASTHIST;
truncate table HOSTMSBST.EXAFMASTHIST;
truncate table HOSTMSBST.GLLOGHIST;
truncate table HOSTMSBST.GLLOGHISTALL;
truncate table HOSTMSBST.GWLOGHIST;
truncate table HOSTMSBST.IODSMSLOGHIST;
truncate table HOSTMSBST.MESSAGELOGHIST;
truncate table HOSTMSBST.MSGRECEIVETEMP_HA_EHIST;
truncate table HOSTMSBST.MSGSENDTEMP_HA_HIST;
truncate table HOSTMSBST.MSGSENDTEMP_HIST;
truncate table HOSTMSBST.ORDERMAP_HA_HIST;
truncate table HOSTMSBST.ORDERPTACK_DELT_HIST;
truncate table HOSTMSBST.ORDERPTACK_HIST;
truncate table HOSTMSBST.ORDERPTADVHIST;
truncate table HOSTMSBST.ORDERPTADV_HIST;
truncate table HOSTMSBST.ORDERPTDEAL_DELT_HIST;
truncate table HOSTMSBST.ORDER_CHANGE_HIST;
truncate table HOSTMSBST.PB_SECURITIES_HIST;
truncate table HOSTMSBST.SEMASTDTLHIST;
truncate table HOSTMSBST.STCCANCELORDERBOOKHIST;
truncate table HOSTMSBST.STCORDERBOOKEXPHIST;
truncate table HOSTMSBST.STCORDERBOOKHIST;
truncate table HOSTMSBST.STCTRADEBOOKEXPHIST;
truncate table HOSTMSBST.STCTRADEBOOKHIST;
truncate table HOSTMSBST.TRADING_RESULT_HIST;
truncate table HOSTMSBST.APPMSGLOGHIST;
truncate table HOSTMSBST.TDTYPSCHMHIST;
truncate table HOSTMSBST.TDMSTSCHMHIST;
truncate table HOSTMSBST.TDLINKHIST;
truncate table HOSTMSBST.IRRATESCHMHIST;
truncate table HOSTMSBST.TBLCFSEHIST;
truncate table HOSTMSBST.TX1195_UPLOADDTLHIST;

